<?php

/**
 * @file
 * Module implementation file.
 */

use Drupal\Core\Access\AccessibleInterface;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Session\AccountInterface;

/**
 * Implements hook_entity_access().
 *
 * NOTE: This is for demonstrations of the APIs. If you were to implement this
 * hook you would not want to do it this way. See the linked article for a
 * better pattern.
 *
 * @see https://www.lullabot.com/articles/maintainable-code-drupal-wrapped-entities
 */
function typed_entity_example_entity_access(EntityInterface $entity, $operation, AccountInterface $account) {
  $repository = typed_entity_repository_manager()->repositoryFromEntity($entity);
  if (!$repository instanceof AccessibleInterface) {
    return AccessResult::neutral();
  }
  $access = $repository->access($operation, $account, TRUE);
  if (!$access->isNeutral()) {
    return $access;
  }
  $wrapped = $repository->wrap($entity);
  if (!$wrapped instanceof AccessibleInterface) {
    return AccessResult::neutral();
  }
  return $wrapped->access($operation, $account, TRUE);
}
